###################################
##  cuckoo Clock simulation.
## Plays the number of cuckoos per hour and 1 on the half hour.
###################################

- alias: Cuckoo Clock
  trigger:
    - platform: time
      minutes: 00
      seconds: 01
    - platform: time
      minutes: 15
      seconds: 00
    - platform: time
      minutes: 30
      seconds: 00
    - platform: time
      minutes: 45
      seconds: 00

  condition:
    - condition: time
      after: '17:44:00'
      before: '18:29:00'
    - condition: template
      value_template: >
        {% if is_state('media_player.kitchen', 'playing') %}
          false
        {% else %}
          true
        {% endif %}

  action:
    - service: script.amp_settings
      data:
        media_player: 'media_player.livingroomcc'
        volume_level: 0.22

    - service: media_player.play_media
      data_template:
        entity_id: media_player.kitchen
        media_content_id: >
          {% if now().strftime("%M")|int != 0 %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/cuckoo-clock-01.wav
          {% else %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
          {% endif %}
        media_content_type: audio/mp4
